#! /bin/sh


# Set headphone volumne
amixer set Headphone 75%

# Start picom
~/.config/picom/launch.sh
# Start hotkey deamon
sxhkd &
# Start polybar
~/.config/polybar/launch.sh
# Set background
feh --bg-fill /usr/share/wallpapers/lake.jpg
# Fix java
wmname LG3D
# Setup keyboard
setxkbmap -option grp:alt_shift_toggle us,dk &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
