#!/bin/sh

# Set wallpaper
nitrogen --restore &
# NetworkManager applet
pkill -x nm-applet; nm-applet &
# Start hotkey deamon
pkill -x sxhkd; sxhkd &
# Start polybar
pkill -x polybar; polybar coolbar &
# Fix java
wmname LG3D
# Lockscreen
light-locker &

bspc monitor -d I II III IV V VI VII VIII IX

bspc rule -a *:st_float state=floating
bspc rule -a *:Origin state=floating

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config top_padding          36
bspc config ignore_ewmh_struts   true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

